import streamlit as st

st.title("ER Diagram Description")
st.header("• We have a Voters Entity Set which contains attributes: Voter ID(Primary Key), Name: a composite attribute split into first name and last name,Age,Address. It has a Weak Entity Set:Phone Number for storing all the phone numbers of the voters as phone number is a multi valued attribute.There is a many one relationship with total participation on both side as one user must have atleast one phone number but may have many phone numbers and one phone number must correspond to exactly one user.It also has another Weak Entity Set:Voter Login which contains the login information of the voter:Username,Password to be used by the user for login.There is a one to one relation between them with total participation as each voter must have exactly one login crendential and each login credential must correspond to exactly one voter.")
st.header("• Similarly we have an Admin Entity Set which contains the same attributes as the Voters Entity Set and also has 2 Weak Entity Sets:Phone Number to store the phone numbers of the admins and Admin Login to store the admins login information.")
st.header("• We have a Voting History Entity Set with attributes:Election ID,Description,Start Time,End Time,Voter Turnout and Winner of an Election that has been completed. Both the Voters and Admins can view the information contained by the table representing this Entity Set after they login.")
st.header("• We then have a Voting Current Entity Set with attributes:Election ID,Description,Start Time,End Time.Both the Voters and Admins can view the information contained by the table representing this Entity Set after they login. Admins can also Edit the Table after Login. It has a Weak Entity Set called Candidate which contains information about the candidates participating in all Elections.This Weak Entity Set can be viewed by both the voters and admins and it can be Edited by the Admins.")
st.header("• We then have a Relationship Set between Voters and Voting Current called Voters Eligible for Voting in a Specific Election which contains Information about which voters can Vote in a Specific Election. This Relationship Set can also be viewed by both the Admins and Voters after login and can be edited by the Admin.")
st.header("• We then have a Vote Counter Relationship set between Voters Eligible for Voting in a Specific Election and Candidate called Vote Counter which contains information about the Election,Voter and the voters Vote.Voters can access the Table for voting.")
st.header("After the End Time of the Election all information pertaining to it in the Voting Current,Candidate,Vote Counter and Voters Eligible for Specific Election will be flushed after retreiving information about the Winner,Voter Turnout etc which will be entered in the Voting History Table.")
